<template>
  <view class="container">
    <view class="add-product-section"><view class="form-item"><text class="label">产品名称:</text><input type="text" v-model="newProductName" placeholder="请输入产品名称" class="input" @input="onProductNameInput" /></view><view class="form-item"><text class="label">基础单价:</text><input type="digit" v-model="newProductPrice" placeholder="请输入基础单价" class="input" /></view><view class="icon-selection" v-if="iconSuggestions.length"><text class="icon-label">选择图标:</text><view class="icon-grid"><view v-for="(suggestion,index) in iconSuggestions" :key="index" class="icon-option" :class="{ 'icon-selected': selectedIcon === suggestion.icon }" @click="selectIcon(suggestion.icon)"><text class="icon-emoji">{{ suggestion.icon }}</text><text class="icon-reason">{{ suggestion.reason }}</text></view></view></view><button @click="addProduct" class="add-btn">添加产品</button></view>
    <view class="product-list"><view v-for="product in store.products" :key="product.id" class="product-item"><view class="product-info"><text class="product-icon">{{ getProductIcon(product.name) }}</text><view class="product-details"><text class="product-name">{{ product.name }}</text><text class="product-price">基础 ¥{{ product.unitPrice.toFixed(2) }}<text v-if="product.colors.length"> · {{ product.colors.length }}种颜色</text></text></view></view><view class="product-controls"><view class="switch-container"><text class="switch-label">显示</text><switch :checked="product.enabled !== false" @change="toggleProductEnabled(product)" color="#007AFF" /></view><view class="product-actions"><button @click="manageColors(product)" class="color-btn">颜色</button><button @click="editProduct(product)" class="edit-btn">编辑</button><button @click="deleteProduct(product.id)" class="delete-btn">删除</button></view></view></view></view>
    <view v-if="colorEditorProduct" class="modal" @click="closeColorEditor"><view class="modal-content" @click.stop><text class="modal-title">{{ colorEditorProduct.name }} · 颜色单价</text><text class="modal-hint">每种颜色可独立计价；历史记录保存的是当时单价。</text><view v-for="(color,index) in editingColors" :key="index" class="color-row"><input v-model="color.name" class="color-input" placeholder="颜色名称" /><input v-model="color.unitPrice" class="price-input" type="digit" placeholder="单价" /><text class="remove-color" @click="removeColor(index)">删除</text></view><button class="add-color-btn" @click="addColor">＋ 添加颜色</button><view class="modal-actions"><button @click="closeColorEditor">取消</button><button class="save-color-btn" @click="saveColors">保存颜色价格</button></view></view></view>
  </view>
</template>
<script setup>
import { ref, onMounted } from 'vue';
import { useAppStore } from '../../stores/app';
import { ProductIconManager } from '@/utils/productIcons.js';
const store=useAppStore(); const newProductName=ref(''); const newProductPrice=ref(''); const selectedIcon=ref(''); const iconSuggestions=ref([]); const colorEditorProduct=ref(null); const editingColors=ref([]);
onMounted(()=>store.initProducts());
function getProductIcon(name){return ProductIconManager.getIcon(name)} function onProductNameInput(){const name=newProductName.value.trim();iconSuggestions.value=name?ProductIconManager.getIconSuggestions(name):[];if(iconSuggestions.value.length&&!selectedIcon.value)selectedIcon.value=iconSuggestions.value[0].icon} function selectIcon(icon){selectedIcon.value=icon}
function addProduct(){const name=newProductName.value.trim(),price=Number(newProductPrice.value);if(!name)return uni.showToast({title:'请输入产品名称',icon:'none'});if(!price||price<=0)return uni.showToast({title:'请输入有效的单价',icon:'none'});const result=store.createProduct({name,unitPrice:price});if(!result.ok)return uni.showToast({title:result.message,icon:'none'});uni.showToast({title:'添加成功',icon:'success'});newProductName.value='';newProductPrice.value='';selectedIcon.value='';iconSuggestions.value=[]}
function editProduct(product){uni.showModal({title:'编辑产品',editable:true,placeholderText:'产品名称',content:product.name,success:res=>{if(res.confirm&&res.content){const result=store.updateProductBasic(product.id,{name:res.content,unitPrice:product.unitPrice});if(!result.ok)uni.showToast({title:result.message,icon:'none'});else uni.showToast({title:'修改成功',icon:'success'})}}})}
function manageColors(product){colorEditorProduct.value=product;editingColors.value=product.colors.map(c=>({name:c.name,unitPrice:String(c.unitPrice)}))} function closeColorEditor(){colorEditorProduct.value=null;editingColors.value=[]} function addColor(){editingColors.value.push({name:'',unitPrice:String(colorEditorProduct.value?.unitPrice||0)})} function removeColor(index){editingColors.value.splice(index,1)}
function saveColors(){const result=store.updateProductColors(colorEditorProduct.value.id,editingColors.value.map(c=>({name:c.name,unitPrice:Number(c.unitPrice)})));if(!result.ok)return uni.showToast({title:result.message,icon:'none'});uni.showToast({title:'颜色价格已保存',icon:'success'});closeColorEditor()}
function deleteProduct(id){const result=store.removeProduct(id);uni.showToast({title:result.ok?'删除成功':result.message,icon:result.ok?'success':'none'})} function toggleProductEnabled(product){const result=store.updateProductEnabled(product.id,!product.enabled);if(!result.ok)uni.showToast({title:result.message,icon:'none'})}
</script>
<style scoped>
.container{padding:20px;background:#f5f5f5;min-height:100vh}.add-product-section,.product-list{background:#fff;border-radius:8px;padding:20px;margin-bottom:20px}.form-item{display:flex;align-items:center;margin-bottom:15px}.label{width:90px;font-size:14px;color:#333}.input{flex:1;border:1px solid #ddd;border-radius:4px;padding:8px 12px;font-size:14px}.icon-selection{margin-top:20px;padding:15px;background:#f8f9fa;border-radius:8px}.icon-label{display:block;font-size:14px;margin-bottom:10px}.icon-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.icon-option{display:flex;flex-direction:column;align-items:center;padding:10px;background:#fff;border:2px solid #e9ecef;border-radius:8px}.icon-selected{border-color:#007aff;background:#e3f2fd}.icon-emoji{font-size:24px}.icon-reason{font-size:10px;color:#666;text-align:center}.add-btn{width:100%;background:#28a745;color:#fff;border:none;border-radius:4px;padding:12px;font-size:16px;margin-top:10px}.product-item{display:flex;justify-content:space-between;align-items:center;padding:15px;border-bottom:1px solid #eee}.product-info{display:flex;align-items:center;flex:1}.product-icon{font-size:24px;margin-right:12px}.product-details{flex:1}.product-name{font-size:16px;color:#333;display:block}.product-price{font-size:14px;color:#ff6b35;margin-top:4px;display:block}.product-controls{display:flex;align-items:center;gap:12px}.switch-container{display:flex;align-items:center;gap:8px}.switch-label{font-size:12px;color:#666}.product-actions{display:flex;gap:6px}.product-actions button{border:none;border-radius:4px;padding:6px 10px;font-size:12px;color:#fff}.color-btn{background:#8e44ad}.edit-btn{background:#007aff}.delete-btn{background:#dc3545}.modal{position:fixed;inset:0;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;z-index:1000}.modal-content{background:#fff;border-radius:18px;padding:24px;width:88%;max-height:80vh;overflow:auto}.modal-title{display:block;text-align:center;font-size:24px;font-weight:700;margin-bottom:10px}.modal-hint{display:block;color:#888;font-size:12px;margin-bottom:18px}.color-row{display:flex;align-items:center;gap:8px;margin-bottom:12px}.color-input{flex:1;border:1px solid #ddd;border-radius:6px;padding:9px}.price-input{width:90px;border:1px solid #ddd;border-radius:6px;padding:9px}.remove-color{color:#dc3545;font-size:12px}.add-color-btn{width:100%;background:#f0f2ff;color:#667eea;border:1px dashed #667eea;border-radius:8px;padding:10px;margin:8px 0 16px}.modal-actions{display:flex;gap:10px}.modal-actions button{flex:1}.save-color-btn{background:#667eea;color:#fff}
</style>
